### ISSUE TITLE
Extension does not work with Maven 3.8.1

### ISSUE THREAD

**Issue by mikaelparkefelt** [heremaps/here-artifact-maven-wagon#53]
If my findings are correct Maven 3.8.1 does not work with com.here.platform.artifact:artifact-wagon:2.0.13
But it works with Maven 3.6.3 and IntelliJ

**Comment by dmitriy-abramov** [comment]
Hi @mikaelparkefelt,

We are looking for a solution of the issue. We prepare a new version of the wagon with the fix.

Dima

**Comment by abanias** [comment]
Hi @mikaelparkefelt!

Please try to use the 2.0.15 version of the artifact wagon and verify that the issue is fixed for you.

**Comment by mikaelparkefelt** [comment]
I have done a quick test and the previous problem seems to be gone. I will add more comments if i get it again.
